services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/bidding
      REDIS_URL: redis://redis:6379
      JWT_SECRET: c763a1fcd0fd4b533e0c7de15327d9abf6c1c033da1a6cb8944c50d70fb76d13
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bidding
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'
